# Render.com deployment configuration for Noveltech Travel Expense Tracker
# This file configures automatic deployment from GitHub

services:
  - type: web
    name: noveltech-expense-tracker
    env: node
    region: oregon  # or singapore for Asia
    plan: free  # upgrade to starter for custom domain
    buildCommand: npm install && npm run build
    startCommand: npm run serve
    runtime: node
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - vite.config.ts
        - index.html
        - .node-version
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add your Firebase environment variables in Render dashboard:
    # VITE_FIREBASE_API_KEY
    # VITE_FIREBASE_AUTH_DOMAIN  
    # VITE_FIREBASE_PROJECT_ID
    # VITE_FIREBASE_STORAGE_BUCKET
    # VITE_FIREBASE_MESSAGING_SENDER_ID
    # VITE_FIREBASE_APP_ID
    
    # Health check endpoint
    healthCheckPath: /healthz
    
    # Auto-deploy from main branch
    autoDeploy: true
